//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NezamEquipment.ServiceLayer.TrasnsBankCity {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InputPaymentType", Namespace="http://schemas.datacontract.org/2004/07/Yaghot")]
    [System.SerializableAttribute()]
    public partial class InputPaymentType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid GroupEarnedIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RealTransactionDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RefrenceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TransNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string transferDescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid GroupEarnedID {
            get {
                return this.GroupEarnedIDField;
            }
            set {
                if ((this.GroupEarnedIDField.Equals(value) != true)) {
                    this.GroupEarnedIDField = value;
                    this.RaisePropertyChanged("GroupEarnedID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RealTransactionDateTime {
            get {
                return this.RealTransactionDateTimeField;
            }
            set {
                if ((this.RealTransactionDateTimeField.Equals(value) != true)) {
                    this.RealTransactionDateTimeField = value;
                    this.RaisePropertyChanged("RealTransactionDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RefrenceNumber {
            get {
                return this.RefrenceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RefrenceNumberField, value) != true)) {
                    this.RefrenceNumberField = value;
                    this.RaisePropertyChanged("RefrenceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TransNo {
            get {
                return this.TransNoField;
            }
            set {
                if ((this.TransNoField.Equals(value) != true)) {
                    this.TransNoField = value;
                    this.RaisePropertyChanged("TransNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string transferDescription {
            get {
                return this.transferDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.transferDescriptionField, value) != true)) {
                    this.transferDescriptionField = value;
                    this.RaisePropertyChanged("transferDescription");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultTransmission", Namespace="http://schemas.datacontract.org/2004/07/Yaghot")]
    [System.SerializableAttribute()]
    public partial class ResultTransmission : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string yaghot_CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string yaghot_ReferenceIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusDescription {
            get {
                return this.StatusDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDescriptionField, value) != true)) {
                    this.StatusDescriptionField = value;
                    this.RaisePropertyChanged("StatusDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string yaghot_Code {
            get {
                return this.yaghot_CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.yaghot_CodeField, value) != true)) {
                    this.yaghot_CodeField = value;
                    this.RaisePropertyChanged("yaghot_Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string yaghot_ReferenceId {
            get {
                return this.yaghot_ReferenceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.yaghot_ReferenceIdField, value) != true)) {
                    this.yaghot_ReferenceIdField = value;
                    this.RaisePropertyChanged("yaghot_ReferenceId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InputPaymentTypeBackup", Namespace="http://schemas.datacontract.org/2004/07/Yaghot")]
    [System.SerializableAttribute()]
    public partial class InputPaymentTypeBackup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid GroupEarnedIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RealTransactionDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RefrenceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TransNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string transferDescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid GroupEarnedID {
            get {
                return this.GroupEarnedIDField;
            }
            set {
                if ((this.GroupEarnedIDField.Equals(value) != true)) {
                    this.GroupEarnedIDField = value;
                    this.RaisePropertyChanged("GroupEarnedID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RealTransactionDateTime {
            get {
                return this.RealTransactionDateTimeField;
            }
            set {
                if ((this.RealTransactionDateTimeField.Equals(value) != true)) {
                    this.RealTransactionDateTimeField = value;
                    this.RaisePropertyChanged("RealTransactionDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RefrenceNumber {
            get {
                return this.RefrenceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RefrenceNumberField, value) != true)) {
                    this.RefrenceNumberField = value;
                    this.RaisePropertyChanged("RefrenceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TransNo {
            get {
                return this.TransNoField;
            }
            set {
                if ((this.TransNoField.Equals(value) != true)) {
                    this.TransNoField = value;
                    this.RaisePropertyChanged("TransNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string transferDescription {
            get {
                return this.transferDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.transferDescriptionField, value) != true)) {
                    this.transferDescriptionField = value;
                    this.RaisePropertyChanged("transferDescription");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InputArchivePayment", Namespace="http://schemas.datacontract.org/2004/07/Yaghot")]
    [System.SerializableAttribute()]
    public partial class InputArchivePayment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IBANField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RealDateTransferField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string transferDescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankName {
            get {
                return this.BankNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BankNameField, value) != true)) {
                    this.BankNameField = value;
                    this.RaisePropertyChanged("BankName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IBAN {
            get {
                return this.IBANField;
            }
            set {
                if ((object.ReferenceEquals(this.IBANField, value) != true)) {
                    this.IBANField = value;
                    this.RaisePropertyChanged("IBAN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OwnerName {
            get {
                return this.OwnerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerNameField, value) != true)) {
                    this.OwnerNameField = value;
                    this.RaisePropertyChanged("OwnerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RealDateTransfer {
            get {
                return this.RealDateTransferField;
            }
            set {
                if ((object.ReferenceEquals(this.RealDateTransferField, value) != true)) {
                    this.RealDateTransferField = value;
                    this.RaisePropertyChanged("RealDateTransfer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string transferDescription {
            get {
                return this.transferDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.transferDescriptionField, value) != true)) {
                    this.transferDescriptionField = value;
                    this.RaisePropertyChanged("transferDescription");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TrasnsBankCity.ITransmission")]
    public interface ITransmission {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransmission/Transfer", ReplyAction="http://tempuri.org/ITransmission/TransferResponse")]
        NezamEquipment.ServiceLayer.TrasnsBankCity.ResultTransmission[] Transfer(NezamEquipment.ServiceLayer.TrasnsBankCity.InputPaymentType inputPayment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransmission/Transfer", ReplyAction="http://tempuri.org/ITransmission/TransferResponse")]
        System.Threading.Tasks.Task<NezamEquipment.ServiceLayer.TrasnsBankCity.ResultTransmission[]> TransferAsync(NezamEquipment.ServiceLayer.TrasnsBankCity.InputPaymentType inputPayment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransmission/TransferBackup", ReplyAction="http://tempuri.org/ITransmission/TransferBackupResponse")]
        NezamEquipment.ServiceLayer.TrasnsBankCity.ResultTransmission[] TransferBackup(NezamEquipment.ServiceLayer.TrasnsBankCity.InputPaymentTypeBackup inputPayment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransmission/TransferBackup", ReplyAction="http://tempuri.org/ITransmission/TransferBackupResponse")]
        System.Threading.Tasks.Task<NezamEquipment.ServiceLayer.TrasnsBankCity.ResultTransmission[]> TransferBackupAsync(NezamEquipment.ServiceLayer.TrasnsBankCity.InputPaymentTypeBackup inputPayment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransmission/ArchivePayment", ReplyAction="http://tempuri.org/ITransmission/ArchivePaymentResponse")]
        NezamEquipment.ServiceLayer.TrasnsBankCity.ResultTransmission ArchivePayment(NezamEquipment.ServiceLayer.TrasnsBankCity.InputArchivePayment inputPayment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransmission/ArchivePayment", ReplyAction="http://tempuri.org/ITransmission/ArchivePaymentResponse")]
        System.Threading.Tasks.Task<NezamEquipment.ServiceLayer.TrasnsBankCity.ResultTransmission> ArchivePaymentAsync(NezamEquipment.ServiceLayer.TrasnsBankCity.InputArchivePayment inputPayment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransmission/Login", ReplyAction="http://tempuri.org/ITransmission/LoginResponse")]
        bool Login(string UserName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransmission/Login", ReplyAction="http://tempuri.org/ITransmission/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string UserName, string Password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITransmissionChannel : NezamEquipment.ServiceLayer.TrasnsBankCity.ITransmission, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransmissionClient : System.ServiceModel.ClientBase<NezamEquipment.ServiceLayer.TrasnsBankCity.ITransmission>, NezamEquipment.ServiceLayer.TrasnsBankCity.ITransmission {
        
        public TransmissionClient() {
        }
        
        public TransmissionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransmissionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransmissionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransmissionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public NezamEquipment.ServiceLayer.TrasnsBankCity.ResultTransmission[] Transfer(NezamEquipment.ServiceLayer.TrasnsBankCity.InputPaymentType inputPayment) {
            return base.Channel.Transfer(inputPayment);
        }
        
        public System.Threading.Tasks.Task<NezamEquipment.ServiceLayer.TrasnsBankCity.ResultTransmission[]> TransferAsync(NezamEquipment.ServiceLayer.TrasnsBankCity.InputPaymentType inputPayment) {
            return base.Channel.TransferAsync(inputPayment);
        }
        
        public NezamEquipment.ServiceLayer.TrasnsBankCity.ResultTransmission[] TransferBackup(NezamEquipment.ServiceLayer.TrasnsBankCity.InputPaymentTypeBackup inputPayment) {
            return base.Channel.TransferBackup(inputPayment);
        }
        
        public System.Threading.Tasks.Task<NezamEquipment.ServiceLayer.TrasnsBankCity.ResultTransmission[]> TransferBackupAsync(NezamEquipment.ServiceLayer.TrasnsBankCity.InputPaymentTypeBackup inputPayment) {
            return base.Channel.TransferBackupAsync(inputPayment);
        }
        
        public NezamEquipment.ServiceLayer.TrasnsBankCity.ResultTransmission ArchivePayment(NezamEquipment.ServiceLayer.TrasnsBankCity.InputArchivePayment inputPayment) {
            return base.Channel.ArchivePayment(inputPayment);
        }
        
        public System.Threading.Tasks.Task<NezamEquipment.ServiceLayer.TrasnsBankCity.ResultTransmission> ArchivePaymentAsync(NezamEquipment.ServiceLayer.TrasnsBankCity.InputArchivePayment inputPayment) {
            return base.Channel.ArchivePaymentAsync(inputPayment);
        }
        
        public bool Login(string UserName, string Password) {
            return base.Channel.Login(UserName, Password);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string UserName, string Password) {
            return base.Channel.LoginAsync(UserName, Password);
        }
    }
}
