// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC.Admin
{
    public class FeaturesController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _ViewStart = "_ViewStart";
                public readonly string web = "web";
            }
            public readonly string _ViewStart = "~/Areas/Admin/Features/_ViewStart.cshtml";
            public readonly string web = "~/Areas/Admin/Features/web.config";
            static readonly _AccountClass s_Account = new _AccountClass();
            public _AccountClass Account { get { return s_Account; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _AccountClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string Login = "Login";
                }
                public readonly string Login = "~/Areas/Admin/Features/Account/Login.cshtml";
            }
            static readonly _EmployeesClass s_Employees = new _EmployeesClass();
            public _EmployeesClass Employees { get { return s_Employees; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _EmployeesClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string _Form = "_Form";
                    public readonly string _FormPass = "_FormPass";
                    public readonly string Add = "Add";
                    public readonly string Details = "Details";
                    public readonly string Edit = "Edit";
                    public readonly string Index = "Index";
                    public readonly string PasswordCahnge = "PasswordCahnge";
                }
                public readonly string _Form = "~/Areas/Admin/Features/Employees/_Form.cshtml";
                public readonly string _FormPass = "~/Areas/Admin/Features/Employees/_FormPass.cshtml";
                public readonly string Add = "~/Areas/Admin/Features/Employees/Add.cshtml";
                public readonly string Details = "~/Areas/Admin/Features/Employees/Details.cshtml";
                public readonly string Edit = "~/Areas/Admin/Features/Employees/Edit.cshtml";
                public readonly string Index = "~/Areas/Admin/Features/Employees/Index.cshtml";
                public readonly string PasswordCahnge = "~/Areas/Admin/Features/Employees/PasswordCahnge.cshtml";
            }
            static readonly _EmployEquipmentClass s_EmployEquipment = new _EmployEquipmentClass();
            public _EmployEquipmentClass EmployEquipment { get { return s_EmployEquipment; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _EmployEquipmentClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string Details = "Details";
                    public readonly string Index = "Index";
                }
                public readonly string Details = "~/Areas/Admin/Features/EmployEquipment/Details.cshtml";
                public readonly string Index = "~/Areas/Admin/Features/EmployEquipment/Index.cshtml";
            }
            static readonly _EquipmentClass s_Equipment = new _EquipmentClass();
            public _EquipmentClass Equipment { get { return s_Equipment; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _EquipmentClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string _Form = "_Form";
                    public readonly string Add = "Add";
                    public readonly string Details = "Details";
                    public readonly string Edit = "Edit";
                    public readonly string Index = "Index";
                    public readonly string ListEquipmentUnit = "ListEquipmentUnit";
                }
                public readonly string _Form = "~/Areas/Admin/Features/Equipment/_Form.cshtml";
                public readonly string Add = "~/Areas/Admin/Features/Equipment/Add.cshtml";
                public readonly string Details = "~/Areas/Admin/Features/Equipment/Details.cshtml";
                public readonly string Edit = "~/Areas/Admin/Features/Equipment/Edit.cshtml";
                public readonly string Index = "~/Areas/Admin/Features/Equipment/Index.cshtml";
                public readonly string ListEquipmentUnit = "~/Areas/Admin/Features/Equipment/ListEquipmentUnit.cshtml";
            }
            static readonly _EquipmentFaultyClass s_EquipmentFaulty = new _EquipmentFaultyClass();
            public _EquipmentFaultyClass EquipmentFaulty { get { return s_EquipmentFaulty; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _EquipmentFaultyClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string _Form = "_Form";
                    public readonly string Add = "Add";
                    public readonly string Details = "Details";
                    public readonly string Edit = "Edit";
                    public readonly string Index = "Index";
                    public readonly string ListEquipmentUnit = "ListEquipmentUnit";
                }
                public readonly string _Form = "~/Areas/Admin/Features/EquipmentFaulty/_Form.cshtml";
                public readonly string Add = "~/Areas/Admin/Features/EquipmentFaulty/Add.cshtml";
                public readonly string Details = "~/Areas/Admin/Features/EquipmentFaulty/Details.cshtml";
                public readonly string Edit = "~/Areas/Admin/Features/EquipmentFaulty/Edit.cshtml";
                public readonly string Index = "~/Areas/Admin/Features/EquipmentFaulty/Index.cshtml";
                public readonly string ListEquipmentUnit = "~/Areas/Admin/Features/EquipmentFaulty/ListEquipmentUnit.cshtml";
            }
            static readonly _HomeClass s_Home = new _HomeClass();
            public _HomeClass Home { get { return s_Home; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _HomeClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string Details = "Details";
                    public readonly string Index = "Index";
                    public readonly string ListEquipmentUnit = "ListEquipmentUnit";
                }
                public readonly string Details = "~/Areas/Admin/Features/Home/Details.cshtml";
                public readonly string Index = "~/Areas/Admin/Features/Home/Index.cshtml";
                public readonly string ListEquipmentUnit = "~/Areas/Admin/Features/Home/ListEquipmentUnit.cshtml";
            }
            static readonly _ProfileClass s_Profile = new _ProfileClass();
            public _ProfileClass Profile { get { return s_Profile; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _ProfileClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string Edit = "Edit";
                    public readonly string Index = "Index";
                }
                public readonly string Edit = "~/Areas/Admin/Features/Profile/Edit.cshtml";
                public readonly string Index = "~/Areas/Admin/Features/Profile/Index.cshtml";
            }
            static readonly _RoleClass s_Role = new _RoleClass();
            public _RoleClass Role { get { return s_Role; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _RoleClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string _Form = "_Form";
                    public readonly string Add = "Add";
                    public readonly string Edit = "Edit";
                    public readonly string Index = "Index";
                    public readonly string NoEditForDefaultRole = "NoEditForDefaultRole";
                }
                public readonly string _Form = "~/Areas/Admin/Features/Role/_Form.cshtml";
                public readonly string Add = "~/Areas/Admin/Features/Role/Add.cshtml";
                public readonly string Edit = "~/Areas/Admin/Features/Role/Edit.cshtml";
                public readonly string Index = "~/Areas/Admin/Features/Role/Index.cshtml";
                public readonly string NoEditForDefaultRole = "~/Areas/Admin/Features/Role/NoEditForDefaultRole.cshtml";
            }
            static readonly _SegmentClass s_Segment = new _SegmentClass();
            public _SegmentClass Segment { get { return s_Segment; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _SegmentClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string Add = "Add";
                    public readonly string Edit = "Edit";
                    public readonly string Index = "Index";
                }
                public readonly string Add = "~/Areas/Admin/Features/Segment/Add.cshtml";
                public readonly string Edit = "~/Areas/Admin/Features/Segment/Edit.cshtml";
                public readonly string Index = "~/Areas/Admin/Features/Segment/Index.cshtml";
            }
            static readonly _SettingClass s_Setting = new _SettingClass();
            public _SettingClass Setting { get { return s_Setting; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _SettingClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string _AsanPardakht = "_AsanPardakht";
                    public readonly string AsanPardakht = "AsanPardakht";
                    public readonly string Sms = "Sms";
                }
                public readonly string _AsanPardakht = "~/Areas/Admin/Features/Setting/_AsanPardakht.cshtml";
                public readonly string AsanPardakht = "~/Areas/Admin/Features/Setting/AsanPardakht.cshtml";
                public readonly string Sms = "~/Areas/Admin/Features/Setting/Sms.cshtml";
            }
            static readonly _SharedClass s_Shared = new _SharedClass();
            public _SharedClass Shared { get { return s_Shared; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _SharedClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string _Layout = "_Layout";
                    public readonly string _LayoutEmpty = "_LayoutEmpty";
                    public readonly string _Message = "_Message";
                }
                public readonly string _Layout = "~/Areas/Admin/Features/Shared/_Layout.cshtml";
                public readonly string _LayoutEmpty = "~/Areas/Admin/Features/Shared/_LayoutEmpty.cshtml";
                public readonly string _Message = "~/Areas/Admin/Features/Shared/_Message.cshtml";
                static readonly _DefaultClass s_Default = new _DefaultClass();
                public _DefaultClass Default { get { return s_Default; } }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public partial class _DefaultClass
                {
                    static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                    public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                    public class _ViewNamesClass
                    {
                        public readonly string _Danger = "_Danger";
                        public readonly string _DefaultDelete = "_DefaultDelete";
                        public readonly string _NoDataForDisplaying = "_NoDataForDisplaying";
                        public readonly string _Success = "_Success";
                        public readonly string _Warning = "_Warning";
                    }
                    public readonly string _Danger = "~/Areas/Admin/Features/Shared/Default/_Danger.cshtml";
                    public readonly string _DefaultDelete = "~/Areas/Admin/Features/Shared/Default/_DefaultDelete.cshtml";
                    public readonly string _NoDataForDisplaying = "~/Areas/Admin/Features/Shared/Default/_NoDataForDisplaying.cshtml";
                    public readonly string _Success = "~/Areas/Admin/Features/Shared/Default/_Success.cshtml";
                    public readonly string _Warning = "~/Areas/Admin/Features/Shared/Default/_Warning.cshtml";
                }
                static readonly _RightMenuClass s_RightMenu = new _RightMenuClass();
                public _RightMenuClass RightMenu { get { return s_RightMenu; } }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public partial class _RightMenuClass
                {
                    static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                    public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                    public class _ViewNamesClass
                    {
                        public readonly string _Employees = "_Employees";
                        public readonly string _Equipment = "_Equipment";
                        public readonly string _EquipmentFaulty = "_EquipmentFaulty";
                        public readonly string _Management = "_Management";
                        public readonly string _Profile = "_Profile";
                        public readonly string _Report = "_Report";
                        public readonly string RightMenu = "RightMenu";
                    }
                    public readonly string _Employees = "~/Areas/Admin/Features/Shared/RightMenu/_Employees.cshtml";
                    public readonly string _Equipment = "~/Areas/Admin/Features/Shared/RightMenu/_Equipment.cshtml";
                    public readonly string _EquipmentFaulty = "~/Areas/Admin/Features/Shared/RightMenu/_EquipmentFaulty.cshtml";
                    public readonly string _Management = "~/Areas/Admin/Features/Shared/RightMenu/_Management.cshtml";
                    public readonly string _Profile = "~/Areas/Admin/Features/Shared/RightMenu/_Profile.cshtml";
                    public readonly string _Report = "~/Areas/Admin/Features/Shared/RightMenu/_Report.cshtml";
                    public readonly string RightMenu = "~/Areas/Admin/Features/Shared/RightMenu/RightMenu.cshtml";
                }
            }
            static readonly _UserClass s_User = new _UserClass();
            public _UserClass User { get { return s_User; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _UserClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string _Form = "_Form";
                    public readonly string Add = "Add";
                    public readonly string Details = "Details";
                    public readonly string Edit = "Edit";
                    public readonly string Index = "Index";
                }
                public readonly string _Form = "~/Areas/Admin/Features/User/_Form.cshtml";
                public readonly string Add = "~/Areas/Admin/Features/User/Add.cshtml";
                public readonly string Details = "~/Areas/Admin/Features/User/Details.cshtml";
                public readonly string Edit = "~/Areas/Admin/Features/User/Edit.cshtml";
                public readonly string Index = "~/Areas/Admin/Features/User/Index.cshtml";
            }
            static readonly _UserAccessListClass s_UserAccessList = new _UserAccessListClass();
            public _UserAccessListClass UserAccessList { get { return s_UserAccessList; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _UserAccessListClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string Index = "Index";
                }
                public readonly string Index = "~/Areas/Admin/Features/UserAccessList/Index.cshtml";
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
